# Generated by Django 3.0 on 2021-07-17 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='medical',
            new_name='medical_type',
        ),
    ]
